# Generated by Django 4.1.5 on 2023-01-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='size',
            new_name='volume',
        ),
        migrations.AddField(
            model_name='commodity',
            name='colume',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
