# Generated by Django 4.1.5 on 2023-01-28 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='proposal_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='commodity',
            field=models.CharField(default='commo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('caad5e4c-9eea-11ed-9d9d-088fc316e797')),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='predicted_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
