# Generated by Django 4.1.5 on 2023-01-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_size_warehouse_volume_commodity_colume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='colume',
            new_name='volume',
        ),
    ]
