# Generated by Django 4.1.5 on 2023-01-28 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_shipment_decision_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='flow',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('555e3e09-9ef1-11ed-a00a-088fc316e797')),
        ),
    ]
