# Generated by Django 4.1.5 on 2023-01-28 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rename_colume_commodity_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_commodities', to='warehouse.category'),
        ),
    ]
