# Generated by Django 4.1.5 on 2023-01-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_commodity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
