# Generated by Django 4.1.5 on 2023-01-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_commodity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='max_quantity',
        ),
    ]
