# Generated by Django 4.1.5 on 2023-01-28 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_remove_warehouse_max_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(blank=True, max_length=255, null=True)),
                ("predicted_price", models.FloatField(blank=True, null=True)),
                ("actual_price", models.FloatField(blank=True, null=True)),
                (
                    "proposal_date",
                    models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0)),
                ),
                (
                    "decision_date",
                    models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0)),
                ),
                (
                    "status",
                    models.CharField(blank=True, default="Pending", max_length=255),
                ),
                (
                    "reciever",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recievers",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senders",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
        ),
    ]
