# Generated by Django 4.1.5 on 2023-01-27 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0))),
            ],
        ),
    ]
